Fixed make-rgbi-pic to cope with --molden and --fchk inputs

diff --git a/rgbi-scripts/make-rgbi-pic b/rgbi-scripts/make-rgbi-pic
--- a/rgbi-scripts/make-rgbi-pic
+++ b/rgbi-scripts/make-rgbi-pic
@@ -43,13 +43,9 @@
 # - mol2chemfig.sty file
 # - cf-pastebin.tex ... the old chemfig.tex
 
-# Any Test.FChk?
-if [ ! -f Test.FChk ]; then
-  echo "Test.FChk not found"
-  exit 1
-fi
-
 # Defaults
+mold=""
+fchk=""
 do_tonto=0
 do_xyz=0
 do_H=0
@@ -57,6 +53,14 @@ do_ci=0
 
 # Process options
 while [[ "$#" > 0 ]]; do case $1 in
+  --molden) 
+    shift
+    mold="$1"
+    ;;
+  --fchk) 
+    shift
+    fchk="$1"
+    ;;
   --no-tonto) do_tonto=0;;
   --do-tonto) do_tonto=1;;
   --do-xyz)   do_xyz=1;;
@@ -74,14 +78,29 @@ fi
 
 # Babel: convert fchk to structure.mol
 rm rgbi-structure.tex
-if [[ do_H -gt 0 ]]; then
-   obabel --gen2d    -ifchk Test.FChk -omol > rgbi-structure.mol # keep H atoms
-   cp rgbi-bondtable+H.tex   rgbi-bondtable.tex
-   cp rgbi-atom-labels+H.tex rgbi-atom-labels.tex
+if [[ -n "$fchk" ]]; then
+  if [[ do_H -gt 0 ]]; then
+     obabel --gen2d    -ifchk $fchk -omol > rgbi-structure.mol # keep H atoms
+     cp rgbi-bondtable+H.tex   rgbi-bondtable.tex
+     cp rgbi-atom-labels+H.tex rgbi-atom-labels.tex
+  else
+     obabel --gen2d -d -ifchk $fchk -omol > rgbi-structure.mol # delete H atoms
+     cp rgbi-bondtable-H.tex   rgbi-bondtable.tex
+     cp rgbi-atom-labels-H.tex rgbi-atom-labels.tex
+  fi
+elif [[ -n "$mold" ]]; then
+  if [[ do_H -gt 0 ]]; then
+     obabel --gen2d    -imolden $mold -omol > rgbi-structure.mol # keep H atoms
+     cp rgbi-bondtable+H.tex   rgbi-bondtable.tex
+     cp rgbi-atom-labels+H.tex rgbi-atom-labels.tex
+  else
+     obabel --gen2d -d -imolden $mold -omol > rgbi-structure.mol # delete H atoms
+     cp rgbi-bondtable-H.tex   rgbi-bondtable.tex
+     cp rgbi-atom-labels-H.tex rgbi-atom-labels.tex
+  fi
 else
-   obabel --gen2d -d -ifchk Test.FChk -omol > rgbi-structure.mol # delete H atoms
-   cp rgbi-bondtable-H.tex   rgbi-bondtable.tex
-   cp rgbi-atom-labels-H.tex rgbi-atom-labels.tex
+   echo "Error: No input provided. Use --fchk or --molden option."
+   exit 1
 fi
 
 # Use CI labels?
